Tms/akhil/heat pump rework
RIT-EVT/TMS pull request #13
Opened 2022-11-03 23:46 UTC by skippynose2

The period was changed to max the frequency. The math is explained within the code. TLDR max frequency can be 950 Hz meaning the period must be 1053 microseconds. Also rewrote the start up pump code. It sets the duty cycle to 100% for 3 ms and then shuts it off.

2022-11-04 20:30 UTC, mjmagee991 requested changes
There are a couple issues with the .hpp file, but otherwise it looks good.

2022-11-04 20:30 UTC, mjmagee991 commented on src/TMS/dev/HeatPump.cpp
> +#include <EVT/utils/time.hpp>
This should be included in the .hpp file, not here

2022-11-04 20:30 UTC, mjmagee991 commented on src/TMS/dev/HeatPump.cpp
> -    } else if (!isInitialized && speed < MIN_INIT_SPEED) {
You should also delete isInitialized from the .hpp file.

2022-11-20 20:12 UTC, mjmagee991 approved these changes
Nice work

2022-11-20 20:44 UTC, mjmagee991 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Heat Pump Cleanup](https://trello.com/c/c4IwWX5w/12-heat-pump-cleanup)

2023-01-02 06:31 UTC, AarC10 approved these changes

2023-01-20 00:16 UTC, ActuallyZach approved these changes

2023-02-02 18:46 UTC, merged