Pee Double You Em RadiatorFan
RIT-EVT/TMS pull request #16
Opened 2023-02-25 17:11 UTC by pro-sper

The fan was updated to use PWM as opposed to GPIO

2023-02-25 18:06 UTC, mjmagee991 requested changes
Two minor issues

2023-02-25 18:06 UTC, mjmagee991 commented on include/TMS/dev/RadiatorFan.hpp
> +#include "EVT/io/PWM.hpp"
Use `<>` for your includes instead of `""`

2023-02-25 18:06 UTC, mjmagee991 commented on src/TMS/dev/RadiatorFan.cpp
> +    time::wait(3);              // turning on the pump for 3 milliseconds (must do according to data sheet)
This is only necessary for the pump, not the fans, so it should be deleted

2023-02-25 18:06 UTC, mjmagee991 commented on src/TMS/dev/RadiatorFan.cpp
> +    this->pwm.setDutyCycle(100);// setting the duty cycle to 100% to initially start the pump
For the fans, they should initialize to off, so the duty cycle should be 0

2023-02-25 19:49 UTC, mjmagee991 commented
![](https://github.trello.services/images/mini-trello-icon.png) [PWM Fan Drivers](https://trello.com/c/YTzmF9B4/124-pwm-fan-drivers)

2023-02-28 00:41 UTC, ishan-renjen commented on src/TMS/dev/RadiatorFan.cpp
>  }// namespace TMS
add newline

2023-02-28 00:42 UTC, ishan-renjen approved these changes

2023-02-28 01:06 UTC, ishan-renjen approved these changes

2023-02-28 01:06 UTC, mjmagee991 approved these changes
Nice work

2023-02-28 05:10 UTC, merged