Resolved minor change concerning the Fan consisting of GPIO Enable
RIT-EVT/TMS pull request #17
Opened 2023-03-04 16:01 UTC by pro-sper

2023-03-04 18:47 UTC, mjmagee991 requested changes
Minor implementation issue

2023-03-04 18:47 UTC, mjmagee991 commented on include/TMS/dev/RadiatorFan.hpp
> +    IO::GPIO& gpio = IO::getGPIO<IO::Pin::PC_1>();
This should be passed as an input to the constructor

2023-03-04 18:47 UTC, mjmagee991 commented on src/TMS/dev/RadiatorFan.cpp
> +        else{
It looks like the autoformatter didn't run on this branch. Make sure it does before you merge

2023-03-07 00:14 UTC, AarC10 approved these changes

2023-03-07 00:58 UTC, ishan-renjen commented on targets/fanSample/main.cpp
> +
remove line

2023-03-07 00:59 UTC, ishan-renjen commented on include/TMS/dev/RadiatorFan.hpp
> +    /** GPIO instance to turn on the fan */
add a newline  between 37 and 38

2023-03-07 00:59 UTC, ishan-renjen approved these changes

2023-03-10 00:57 UTC, DeLozM8 approved these changes

2023-04-27 18:17 UTC, mjmagee991 approved these changes

2023-04-28 00:09 UTC, merged