TooMuchStress
RIT-EVT/TMS pull request #20
Opened 2024-02-06 01:03 UTC by BB9653

TMS CANOpen Object Dictionary upgrade.

2024-02-09 04:28 UTC, mjmagee991 requested changes
Two small details

2024-02-09 04:28 UTC, mjmagee991 commented on include/TMS/TMS.hpp
> +        TRANSMIT_PDO_MAPPING_START_KEY_1AXX(0, 4),
Add comments to the dictionary like the examples to make it a bit more clear

2024-02-09 04:28 UTC, mjmagee991 commented on targets/TMS/main.cpp
>      DEV::Timer& timer = DEV::getTimer<DEV::MCUTimer::Timer16>(100);
There is some other stuff in this function that should be updated to the new standard. Don't worry about the stuff in the while loop just yet

2024-02-21 16:37 UTC, mjmagee991 approved these changes
Nice work!

2024-02-24 15:09 UTC, ActuallyTaylor approved these changes
Solid CAN

2024-02-24 15:10 UTC, merged